version: "3.9"

services:
  db:
    image: postgres:15
    container_name: waifu_bot_db
    environment:
      POSTGRES_DB: waifu_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d waifu_bot"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7
    container_name: waifu_bot_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: waifu_bot_app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/waifu_bot
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./:/app
    command: ["python", "-m", "bot.main"]
    restart: unless-stopped

volumes:
  postgres_data:



